

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 341)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 491, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(90, 120, 191, 61))
        self.label.setStyleSheet("font: 20pt \"Impact\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(290, 120, 141, 61))
        self.label_2.setStyleSheet("font: 20pt \"Impact\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(90, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 190, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(70, 50, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 131, 31))
        self.label_3.setStyleSheet("font: 16pt \"Impact\";")
        self.label_3.setObjectName("label_3")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.page_2)
        self.commandLinkButton.setGeometry(QtCore.QRect(400, 270, 71, 41))
        self.commandLinkButton.setIconSize(QtCore.QSize(0, 20))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.page_3)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(350, 280, 131, 41))
        self.commandLinkButton_2.setIconSize(QtCore.QSize(0, 20))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.listView = QtWidgets.QListView(self.page_3)
        self.listView.setGeometry(QtCore.QRect(20, 30, 461, 241))
        self.listView.setObjectName("listView")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Запись "))
        self.label_2.setText(_translate("MainWindow", "Чтение"))
        self.pushButton.setText(_translate("MainWindow", "Далее"))
        self.pushButton_2.setText(_translate("MainWindow", "Далее"))
        self.label_3.setText(_translate("MainWindow", "Ввод данных"))
        self.commandLinkButton.setText(_translate("MainWindow", "Запись"))
        self.pushButton_3.setText(_translate("MainWindow", "назад"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Читать данные"))
        self.pushButton_4.setText(_translate("MainWindow", "назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
